# Generated by Django 4.2.7 on 2023-12-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_air', '0002_sneakers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sneakers',
            old_name='types',
            new_name='type',
        ),
        migrations.AddField(
            model_name='sneakers',
            name='character',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
    ]
