# Generated by Django 4.2.7 on 2023-12-10 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_air', '0008_advertising'),
    ]

    operations = [
        migrations.AddField(
            model_name='sneakers',
            name='last_name',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
    ]
