# Generated by Django 4.2.7 on 2023-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('n_air', '0012_alter_register_phone'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AddField(
            model_name='register',
            name='message',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='register',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
