# Generated by Django 4.2.7 on 2023-12-10 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('n_air', '0014_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='message',
        ),
    ]
